const styles = {
  app: {
    display: "flex",
    height: "100vh",
    width: "100%",
    fontFamily: "Segoe UI, Tahoma, Geneva, Verdana, sans-serif",
    background: "#f9f9fb",
    color: "#333",
    margin: 0,
  },
  sidebar: {
    width: "250px",
    background: "linear-gradient(180deg, #6a11cb, #2575fc)",
    color: "white",
    padding: "20px",
    boxShadow: "2px 0 8px rgba(0, 0, 0, 0.15)",
    display: "flex",
    flexDirection: "column",
  },
  logo: {
    fontSize: "1.3rem",
    fontWeight: "bold",
    marginBottom: "30px",
    textAlign: "center",
  },
  navList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  navLink: {
    textDecoration: "none",
    color: "#fff",
    fontSize: "1rem",
    fontWeight: "500",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.3s ease",
    padding: "10px",
    borderRadius: "8px",
    marginBottom: "10px",
  },
  main: {
    flex: 1,
    padding: "40px",
    overflowY: "auto",
    background: "#ffffff",
  },
  heading: {
    fontSize: "2rem",
    color: "#444",
    textAlign: "center",
    marginTop: "40px",
  },
  page: {
    padding: "20px",
    textAlign: "center",
    background: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
    margin: "20px auto",
    maxWidth: "600px",
  },
  textarea: {
    width: "100%",
    height: "120px",
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    marginBottom: "15px",
    fontSize: "1rem",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    marginBottom: "15px",
    fontSize: "1rem",
  },
  button: {
    padding: "10px 18px",
    fontSize: "1rem",
    border: "none",
    borderRadius: "8px",
    background: "linear-gradient(90deg, #2575fc, #6a11cb)",
    color: "white",
    cursor: "pointer",
    transition: "0.3s",
  },
};

export default styles;